### ISSUE TITLE
Does not work after switching scenes

### ISSUE THREAD

**Issue by Avitale34** [basicer/foundryvtt-t-is-for-target#1]
Love this module! However it seems like after switching scenes it no longer works. To fix the whole game needs to be reloaded for the module to work again.

**Comment by basicer** [comment]
Hey, sorry I didnt see this sooner.  Ill get this fixed tonight!

**Comment by Avitale34** [comment]
No worries at all! Thank you!

**Comment by basicer** [comment]
Hey @Avitale34 , I can't seem to reproduce this on my local instance of foundry.  What modules are you using?

**Comment by Avitale34** [comment]
Are you on discord I can send you my module file?

**Comment by earlSt1** [comment]
I've been having the same issue, and managed to fix it before my session by changing line 22 to this:

```js
Hooks.on('canvasReady',TIsForTarget.ready);
````

Awesome module btw!  :smile:

**Comment by earlSt1** [comment]
@basicer Great stuff, just updated to 0.3 and can confirm I no longer get this issue. Thanks for the quick response! 😃
