### ISSUE TITLE
Conflicts with other Modules

### ISSUE THREAD

**Issue by LamahHerder** [basicer/foundryvtt-t-is-for-target#3]
FYI for others that may run into issue
Monk's little details new version conflicts with this
https://github.com/ironmonk88/monks-little-details/issues/34

`Adding the option to briefly switch between layers by holding down a key and pressing Shift+key will change the layer. This should let you switch briefly to another layer such as the Tiles layer to hide or show a tile before releasing the key and going back tot he token layer. Current keys are assigned as r=tokens, t-tiles, y-lighting, u-sounds, i-terrain (if you have the Terrain Layer module installed)`

Took me a while to figure out what changed
First had to find which module was conflicting (luckily Find the Culprit helps)

All fixed now, but others may run into this issue with same module or different module and not be able to fix or figure it out

Recommend using https://foundryvtt.com/packages/lib-df-hotkeys to avoid conflict with other mods

**Comment by basicer** [comment]
Thanks for the suggestion!

v0.4 now integrates with lib-df-hotkeys
